services:
  container1:
    build : .
    image: therealflash/tp2_worker
    ports:
      - "5000:5000"

  container2:
    build : .
    image: therealflash/tp2_worker
    ports:
      - "5001:5000"
